import WButton from './src/button'
import WButtonGroup from './src/button-group'
import WIcon from './src/icon'
import WInput from './src/input'
import WRow from './src/row'
import WCol from './src/col'
import WLayout from './src/layout'
import WContent from './src/content'
import WFooter from  './src/footer'
import WHeader from './src/header'
import WSider from './src/sider'
import WToast from './src/toast'
import WPlugin from './src/plugin'
import WTabs from './src/tabs'
import WTabsHead from './src/tabs-head'
import WTabsItem from './src/tabs-item'
import WTabsBody from './src/tabs-body'
import WTabsPane from './src/tabs-pane'
import WPopover from './src/popover'
import WCollapse from './src/collapse'
import WCollapseItem from './src/collapse-item'

export default {WButtonGroup,WButton,WIcon,WInput,WRow,WCol,WLayout,WContent,WFooter,WHeader,WSider,WToast,WPlugin,WTabs,WTabsHead,WTabsItem,WTabsBody,WTabsPane,WPopover,WCollapse,WCollapseItem
}